@startuml
'https://plantuml.com/sequence-diagram

hide footbox

participant Java2Puml.class as main
participant "doclet : Doclet" as doclet
participant ToolProvider.class as TP
participant "toolProvider : ToolProvider" as toolProvider
participant "environnement : DocletEnvironnement" as environnement

[o-> main ++: main(args)
|||

main -> TP ++ : findFirst("javadoc")

'Celui là pas sûr
TP -->> toolProvider ** : <<Create>> ToolProvider()

return toolProvider = findFirst()

main -> toolProvider ++ : run(System.out, System.err, arguments)

toolProvider -->> doclet ** : <<Create>> Doclet()

toolProvider -> doclet ++: init(locale, reporter)
deactivate

toolProvider -> doclet ++: getSupportedOptions()
return supportedOptions = getSupportedOptions()
|||

toolProvider -> doclet ++ : getSupportedSourceVersion()
return supportedSourceVersion = getSupportedSourceVersion()
|||

'toolProvider -->> environnement **: <<Create>> DocletEnvironnement()

alt run is success

    toolProvider -> doclet ++: run(environment)
    return run_success = run()

end alt





@enduml