@startuml
'https://plantuml.com/class-diagram

class PumlDoclet
{
    + init(Locale:locale, Reporter:reporter) {redefined Doclet::init()}
    + getName() : String {redefined Doclet::getName()}
    + getSupportedOptions() : Set<? extends Option> {redefined Doclet::getSupportedOptions()}
    + getSupportedSourceVersion() : SourceVersion {redefined Doclet::getSupportedSourceVersion()}
    + run(DocletEnvironment:environment) : Boolean {redefined Doclet::run()}
}
class ToolProvider
{
    + findFirst(name : String) : ToolProvider
}


class Java2Puml
{
    + {static} main(String[]:args)
}

class PumlDiagram
{
    - repertoireDestination : String
    - nomFichierACree : String
    - environment : DocletEnvironment

    + <<Create>> PumlDiagram(repertoireDestination : String, nomFichierACree : String, environment : DocletEnvironment)
    + getRepertoireDestination() : String
    + getNomFichierACreer() : String
    + getEnvironment() : DocletEnvironment

    + generePuml()
    + recupClasses(environment : DocletEnvironment) : Element[*]
    + ecrisCodePuml(classes : Element[*]) : String
    + getStereotype(classe : Element) : String
    + getPrimitiveFieldsNamesAndConstEnum(classe : Element) : String[*]
    + ajouteTypeElement(codePumlDeBase : String, classe : Element) : StringBuilder
    + ajouteChamps(codePumlDeBase : StringBuilder, classe : Element) : StringBuilder

}

interface Doclet <<interface>>
{
    + init(Locale:locale, Reporter:reporter)
    + getName() : String
    + getSupportedOptions() : Set<? extends Option>
    + getSupportedSourceVersion() : SourceVersion
    + run(DocletEnvironment:environment) : Boolean
}
interface "Doclet.Option" as docletOption <<interface>>
{
    + getArgumentCount() : int
    + getDescription() : String
    + getKind() : Option.Kind
    + getNames() : String[*]
    + getParameters() : String
    + process(option : String, arguments : String[*]) : Boolean
}

enum "Doclet.Option.Kind" as docletOptionKind <<enum>>
{
    EXTENDED
    STANDARD
    OTHER
}

interface DocletEnvironment <<interface>>
{
    + getSpecifiedElements() : Element[]
    + getIncludedElements() : Element[]
    + getDocTrees() : DocTrees
    + getElementUtils() : Elements
    + getTypeUtils() : Types
    + isIncluded(e : Element) : Boolean
    + isSelected(e : Element) : Boolean
    + getFileKind(type : TypeElement) : Kind
}
enum "DocletEnvironment.ModuleMode" as ModuleMode <<enum>>
{
    API
    ALL
}
DocletEnvironment ..> ModuleMode : <<use>>

interface Element
{
    + getEnclosedElements() : Element
    + getEnclosingElement() : Element[*]
    + getKind() : ElementKind
    + getModifiers() : Modifier[]
    + getSimpleName() : Name
    + equals(obj : Object) : Boolean {redefined Object::equals()}
    + asType() : TypeMirror
}

class Locale implements Cloneable, Serializable
interface Reporter <<interface>>
Doclet ..> Locale : <<use>>
Doclet ..> Reporter : <<use>>


Java2Puml ..> ToolProvider : <<instanciate>>

PumlDiagram ..> DocletEnvironment : <<use>>
Doclet ..> DocletEnvironment : <<use>>
docletOption <.. Doclet : <<use>>
docletOptionKind <.. docletOption : <<use>>

PumlDoclet ...|> Doclet
Java2Puml " 1\t" -- "1\ndoclet" PumlDoclet : appelle >
PumlDoclet  " 1" ...> "1\ndiagrammeUML" PumlDiagram : <<instanciate>>
PumlDiagram ..> Element : <<use>>


enum ElementKind
{
    ANNOTATION_TYPE
    CLASS
    CONSTRUCTOR
    ENUM
    ENUM_CONSTANT
    EXCEPTION_PARAMETER
    FIELD
    INSTANCE_INIT
    INTERFACE
    LOCAL_VARIABLE
    METHOD
    MODULE
    OTHER
    PACKAGE
    PARAMETER
    RESSOURCE_VARIABLE
    STATIC_INIT
    TYPE_PARAMETER
    isClass()
    isField()
    isInterface()
}

class DocTrees extends Trees
{
    + <<Create>> DocTrees()

    + getBreakIterator() : BreakIterator
    + getDocCommentTree(path : TreePath) : DocCommentTree
    + getDocCommentTree(e : Element) : DocCommentTree
    + getDocCommentTree(fileObject : FileObject) : DocCommentTree

    + getDocTreePath(fileObject : FileObject, packageElement : PackageElement) : DocTreePath
    + getElement(path : DocTreePath) : Element
    + getType(path : DocTreePath) : TypeMirror
    + getFirstSentence(list : DocTree[*]) : DocTree[*]
    + getSourcePositions() : DocSourcePositions
    + getDocTreeFactory() : DocTreeFactory
    + getCharacters(tree : EntityTree) : String
}

@enduml