@startuml
'https://plantuml.com/class-diagram

class PumlDoclet
class ToolProvider


class Java2Puml

class PumlDiagram

interface Doclet <<interface>>
interface "Doclet.Option" as docletOption <<interface>>
enum "Doclet.Option.Kind" as docletOptionKind <<enum>>

interface DocletEnvironnement <<interface>>

Java2Puml ..> ToolProvider : <<instanciate>>

PumlDoclet ..> DocletEnvironnement : <<use>>
Doclet ..> DocletEnvironnement : <<use>>
docletOption ..> Doclet : <<in>>
docletOptionKind ..> docletOption : <<in>>

PumlDoclet ...|> Doclet
Java2Puml " 1\t" -- "1\ndoclet" PumlDoclet : appelle >
PumlDoclet  " 1" ...> "1\ndiagrammeUML" PumlDiagram : <<instanciate>>



@enduml