@startuml

package [western]{
	class Histoire4{
+ <<Create>> Histoire4()
+ {static} main(args:String[*])
}


class Histoire2{
+ <<Create>> Histoire2()
+ {static} main(args:String[*])
}


class Boisson{
+ <<Create>> Boisson(nom:String, genre:Genre)
+  getNom() : String
+  getGenre() : Genre
+  getNomAvecArticleIndefini() : String
+  getNomAvecArticlePartitif() : String
+  getNomAvecArticleDefini() : String
+  getNomAvecPreposition(preposition:String) : String
}
Boisson o-- "1\n-substantif" Substantif : >
Boisson o-- "1\n+EAU" Boisson : >


class Personnage implements Nommable{
	-  nom : String 
+ <<Create>> Personnage(nom:String)
+ <<Create>> Personnage(nom:String, boisson:Boisson)
+  dire(texte:String)
+  sePresenter()
+  boire(boisson:Boisson)
+  boire()
+  getNom() : String
+  getBoisson() : Boisson
+ {static} getPseudos(personnages:Nommable[*]) : String
+ {static} getBoissonParDefaut() : Boisson
}
Personnage o-- "1\n-BOISSON_PAR_DEFAUT" Boisson : >
Personnage o-- "1\n-boisson" Boisson : >
Personnage ..> Boisson : <<use>>


class Dame extends Personnage{
	-  estLibre : Boolean 
+ <<Create>> Dame(nom:String)
+ <<Create>> Dame(nom:String, boisson:Boisson)
+  getPseudo() : String
+  seFaireKidnapper(horsLaLoi:Horslaloi)
+  seFaireLiberer(cowBoy:Cowboy)
+  estLibre() : Boolean
+  sePresenter()
+ {static} getBoissonParDefaut() : Boisson
+ {static} setBoissonParDefaut(boisson:Boisson)
+  getRavisseur() : Horslaloi
}
Dame o-- "1\n-sauveur" Cowboy : >
Dame o-- "1\n-ravisseur" HorsLaLoi : >
Dame o-- "1\n-boissonParDefaut" Boisson : >
Dame ..> Cowboy : <<use>>
Dame ..> Boisson : <<use>>


class Brigand extends Personnage implements HorsLaLoi{
	# {static} LOOK_PAR_DEFAUT : String 
	-  look : String 
	-  recompense : Integer 
	-  estLibre : Boolean 
+ <<Create>> Brigand(nom:String)
+ <<Create>> Brigand(nom:String, boisson:Boisson)
+ <<Create>> Brigand(nom:String, boisson:Boisson, look:String)
+  getLook() : String
+  getRecompense() : Integer
+  estLibre() : Boolean
+  kidnapper(dame:Dame)
+  seFaireCapturer(cowBoy:Cowboy)
+  seFaireTirerDessus(cowBoy:Cowboy)
+  getPseudo() : String
+  getCaptives() : Dame[*]
+  sePresenter()
+ {static} getBoissonParDefaut() : Boisson
+ {static} setBoissonParDefaut(boisson:Boisson)
}
Brigand o-- "*\n-captives" Dame : >
Brigand o-- "1\n-gardien" Cowboy : >
Brigand o-- "1\n-boissonParDefaut" Boisson : >
Brigand ..> Cowboy : <<use>>
Brigand ..> Dame : <<use>>
Brigand ..> Boisson : <<use>>


class Ripou extends Cowboy implements HorsLaLoi{
+ <<Create>> Ripou(nom:String)
+ <<Create>> Ripou(nom:String, boisson:Boisson)
+ <<Create>> Ripou(nom:String, boisson:Boisson, look:String)
+  getLook() : String
+  estLibre() : Boolean
+  getRecompense() : Integer
+  kidnapper(dame:Dame)
+  getCaptives() : Dame[*]
+  seFaireCapturer(cowBoy:Cowboy)
+  seFaireTirerDessus(cowBoy:Cowboy)
+  getPseudo() : String
+  sePresenter()
+  liberer(dame:Dame)
}
Ripou o-- "1\n-brigand" Brigand : >
Ripou ..> Dame : <<use>>
Ripou ..> Cowboy : <<use>>


interface HorsLaLoi <<interface>> extends Nommable{
+  estLibre() : Boolean
+  getRecompense() : Integer
+  kidnapper(dame:Dame)
+  seFaireCapturer(cowBoy:Cowboy)
+  seFaireTirerDessus(cowBoy:Cowboy)
+  getLook() : String
+  getCaptives() : Dame[*]
}
HorsLaLoi ..> Cowboy : <<use>>
HorsLaLoi ..> Dame : <<use>>


enum Genre <<enum>>{
	FEMININ
	MASCULIN
}


interface Nommable <<interface>>{
+  getNom() : String
+  getPseudo() : String
}


class Cowboy extends Personnage{
	-  gains : Integer 
+ <<Create>> Cowboy(nom:String)
+ <<Create>> Cowboy(nom:String, boisson:Boisson)
+  getPseudo() : String
+  liberer(dame:Dame)
+  liberer(captives:Dame[*])
+  capturer(horsLaLoi:Horslaloi)
+  tirerSur(brigand:Horslaloi)
+  sePresenter()
+ {static} getBoissonParDefaut() : Boisson
+ {static} setBoissonParDefaut(boisson:Boisson)
}
Cowboy o-- "*\n-captures" HorsLaLoi : >
Cowboy o-- "1\n-boissonParDefaut" Boisson : >
Cowboy ..> Boisson : <<use>>
Cowboy ..> Dame : <<use>>


class Substantif{
	-  nom : String 
+ <<Create>> Substantif(nom:String, genre:Genre)
+  getNom() : String
+  getGenre() : Genre
+  toString() : String
+ {static} isVowel(c:String) : Boolean
+ {static} startsWithVowel(s:String) : Boolean
+  getArticleIndefini() : String
+  avecArticleIndefini() : String
+ {static} getArticleDefini(genre:Genre) : String
+  getArticleDefini() : String
+  avecArticleDefini() : String
+ {static} faireElision(article:String) : String
+  elision() : Boolean
+  getArticlePartitif() : String
+  avecArticlePartitif() : String
+  avecElision(article:String) : String
+  avecPreposition(preposition:String) : String
}
Substantif o-- "1\n-genre" Genre : >


class Narrateur extends Personnage{
+ <<Create>> Narrateur()
+ <<Create>> Narrateur(nom:String)
+  dire(texte:String)
+  boire(boisson:Boisson)
+  boire()
+  getPseudo() : String
}
Narrateur ..> Boisson : <<use>>


}
@enduml
