@startuml

package [western]{
	class Boisson{
}
Boisson -- String[]
Boisson -- HorsLaLoi[]
Boisson -- Dame[*]
Boisson -- Brigand>
Boisson -- Cowboy>
Boisson -- Substantif
Boisson -- Boisson


class Brigand extends Personnage implements HorsLaLoi{
	recompense
	estLibre
}
Brigand -- Dame[*]
Brigand -- Cowboy
Brigand -- Boisson


class Cowboy extends Personnage{
	gains
}
Cowboy -- HorsLaLoi>
Cowboy -- Boisson


class Dame extends Personnage{
	estLibre
}
Dame -- Cowboy
Dame -- HorsLaLoi
Dame -- Boisson


enum Genre <<enum>>{
	FEMININ
	MASCULIN
}


class Histoire2{
}


class Histoire4{
}


interface HorsLaLoi <<interface>> extends Nommable{
}


class Narrateur extends Personnage{
}


interface Nommable <<interface>>{
}


class Personnage implements Nommable{
}
Personnage -- Boisson


class Ripou extends Cowboy implements HorsLaLoi{
}
Ripou -- Brigand


class Substantif{
}
Substantif -- Genre


}
@enduml
