@startuml

class Histoire4{
}

class Histoire2{
}

class Boisson{
}

class Personnage{
}

class Dame{
	estLibre
}

class Brigand{
	recompense
	estLibre
}

class Ripou{
}

interface HorsLaLoi <<interface>>{
}

enum Genre <<enum>>{
	FEMININ
	MASCULIN
}

interface Nommable <<interface>>{
}

class Cowboy{
	gains
}

class Substantif{
}

class Narrateur{
}


@enduml
